### ISSUE TITLE
Jill's checklist

### ISSUE THREAD

**Issue by dlstrong** [data-carpentry-for-agriculture/trial-lesson#10]
- [x]  Vector vs raster
- [x] Function slides/Omelet making machine
- [x] Weird maps
- [x] Work on draft of Intro to R

**Comment by jnaiman** [comment]
1. Vector vs. raster: found in slides 41-91 here: https://uiuc-ischool-dataviz.github.io/spring2020/week02/lecture02.html

The images for these slides are found in: 
 * https://github.com/UIUC-iSchool-DataViz/spring2020/tree/master/week02/images
 * https://github.com/UIUC-iSchool-DataViz/spring2020/tree/master/week02/diagrams

**Comment by jnaiman** [comment]
3. Weird Maps

Found on slides 26-55 (though, there are a few slides after): https://uiuc-ischool-dataviz.github.io/spring2019online/week08/lecture08.html

Images are available: https://github.com/UIUC-iSchool-DataViz/spring2019online/tree/master/week08/images

**Comment by jnaiman** [comment]
2. Function Slides/Omelets

HTML-version slides are here (71-90): https://jnaiman.github.io/csci-p-14110/lesson01/lecture01_p1.html

These slides are actually just a bunch of jpegs: https://github.com/jnaiman/csci-p-14110/blob/master/lesson01/images/flowControlSlides/

**Comment by jnaiman** [comment]
Closing and moving the finalizing of intro to R/Rstudio to other lesson
